name: Update Working Dir from Github config repo

on:
  repository_dispatch:
    types: working-dir-update

jobs:
  update-buildpack-toml:
    runs-on: ubuntu-latest
    name: Update buildpack.toml
    steps:

    - name: Temp print
      run: |
        echo "received event"
        echo "${{ github.event.client_payload }}"

    # - name: Parse ID and Version
    #   id: dependency
    #   run: |
    #     echo "::set-output name=id::$(jq -r .client_payload.dependency.id ${{ github.event_path }})"
    #     echo "::set-output name=version::$(jq -r .client_payload.dependency.version ${{ github.event_path }})"
    #
    # - name: Checkout
    #   uses: actions/checkout@v2
    #
    # - name: Checkout Branch
    #   run: |
    #     git checkout \
    #       -b "dependency-update/${{ steps.dependency.outputs.id }}/${{ steps.dependency.outputs.version }}"
    #
    # - name: Update buildpack.toml
    #   uses: paketo-buildpacks/github-config/actions/dependency/update@receive-dependency-update
    #
    # - name: Commit
    #   run: |
    #     git config --global user.email "paketobuildpacks@gmail.com"
    #     git config --global user.name "paketo-bot"
    #     git commit \
    #       --all \
    #       --message "Updating ${{ steps.dependency.outputs.id }} to ${{ steps.dependency.outputs.version }} in buildpack.toml"
    #
    # - name: Push Branch
    #   run: |
    #     git push \
    #       --set-upstream origin "dependency-update/${{ steps.dependency.outputs.id }}/${{ steps.dependency.outputs.version }}"
    #
    # - name: Open Pull Request
    #   run: |
    #     curl "https://api.github.com/repos/${{ github.repository}}/pulls" \
    #       -H "Authorization: token ${{ github.token }}" \
    #       -X POST \
    #       --data '{
    #         "head": "dependency-update/${{ steps.dependency.outputs.id }}/${{ steps.dependency.outputs.version }}",
    #         "base": "master",
    #         "title": "Update ${{ steps.dependency.outputs.id }}",
    #         "body": "Updates ${{ steps.dependency.outputs.id }} to ${{ steps.dependency.outputs.version }}"
    #       }'
    #
