name: Update Working Dir from Github config repo

on:
  repository_dispatch:
    types: working-dir-update

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update github config
    steps:

    - name: parse inputs
      id: read-inputs
      run: |
        echo "::set-output name=commit::$(jq -r .client_payload.commit ${{ github.event_path }})"
        echo "::set-output name=srcpath::$(jq -r .client_payload.srcpath ${{ github.event_path }})"
        echo "::set-output name=dstpath::$(jq -r .client_payload.dstpath ${{ github.event_path }})"

    # checkout github-config @$commit
    - name: Checkout github-config repo
      uses: actions/checkout@v2
      with:
        repository: thitch97/github-config
        ref: "${{ steps.read-inputs.outputs.commit }}"
        path: src-repo

    # checkout the dst-repo
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: dst-repo

    - name: Checkout PR Branch
      id: pr-branch
      run: |
        BRANCH_NAME="github-config-$(git -C nodejs rev-parse HEAD | head -c7)"
        git -C dst-repo checkout -b "$BRANCH_NAME"
        echo "::set-output name=branch::$BRANCH_NAME"

    - name: copy stuff
      run: |
        echo "pwd is $(pwd)"
        cd "${{ github.workspace }}"
        cp -rf "src-repo${{ steps.read-inputs.outputs.srcpath }}" "dst-repo${{ steps.read-inputs.outputs.dstpath }}"

    - name: Commit
      run: |
        echo "pwd is $(pwd)"
        cd "${{ github.workspace }}"/dst-repo
        git config --global user.email "paketobuildpacks@paketo.io"
        git config --global user.name "paketo-bot"
        git add ".${{ steps.read-inputs.outputs.dstpath }}"
        git commit --message "Updating stuff"

    - name: Push Branch
      run: |
        echo "pwd is $(pwd)"
        cd "${{ github.workspace }}"/dst-repo
        git push --set-upstream origin "${{ steps.pr-branch.outputs.branch }}"

    - name: Open Pull Request
      run: |
        curl "https://api.github.com/repos/${{ github.repository }}/pulls" \
          -H "Authorization: token ${{ github.token }}" \
          -X POST \
          --data '{
            "head": "${{ steps.pr-branch.outputs.branch }}",
            "base": "master",
            "title": "Update stuff",
            "body": "Updates stuff from github-config"
          }'
